version: "3.8"

services:
  # replication_manager_delay:
  #   image: python:3.9-slim
  #   container_name: replication_manager_delay
  #   networks:
  #     - autofailover
  #   entrypoint: [
  #     "bash",
  #     "-c",
  #     "apt-get update && apt-get -y install netcat && sleep 20 && python3 -m http.server 5000"
  #   ]
  #   healthcheck:
  #     test: [ "CMD", "nc", "-z", "localhost", "5000" ]
  #     interval: 15s
  #     timeout: 10s
  #     retries: 5

  replication_manager:
    build: ./replication-manager
    image: replication-manager
    container_name: replication_manager
    ports:
      - target: 10001
        published: 3000
        mode: host
    depends_on:
      mysql_master:
        condition: service_healthy
      mysql_slave:
        condition: service_healthy
      # replication_manager_delay:
      #   condition: service_healthy
    volumes:
      - ./replication-manager/config.toml:/etc/replication-manager/config.toml
      - ./replication-manager/autorejoin-gtid.sh:/opt/autorejoin-gtid.sh
    networks:
      - autofailover

  mysql_master:
    build: ./mysql/master
    image: mysql-master:5.7
    container_name: mysql_master
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
    volumes:
      - mysql_master:/var/lib/mysql
      - ./mysql/master/mysql.cnf:/etc/my.cnf
    networks:
      - autofailover
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3306" ]
      interval: 15s
      timeout: 10s
      retries: 5

  mysql_master_init:
    image: mysql-master:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
    volumes:
      - ./mysql/master/replication_setup.sql:/replication_setup.sql
    networks:
      - autofailover
    depends_on:
      mysql_master:
        condition: service_healthy
    entrypoint:
      [
        "bash",
        "-c",
        "mysql -u root -ppass123 -h mysql_master < replication_setup.sql"
      ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 2s

  mysql_slave:
    build: ./mysql/slave
    image: mysql-slave:5.7
    container_name: mysql_slave
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
    volumes:
      - mysql_slave:/var/lib/mysql
      - ./mysql/slave/mysql.cnf:/etc/my.cnf
    networks:
      - autofailover
    depends_on:
      mysql_master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3306" ]
      interval: 15s
      timeout: 10s
      retries: 5

  mysql_slave_init:
    image: mysql-slave:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
    volumes:
      - ./mysql/slave/replication_setup.sql:/replication_setup.sql
    networks:
      - autofailover
    depends_on:
      mysql_slave:
        condition: service_healthy
    entrypoint:
      [
        "bash",
        "-c",
        "mysql -u root -ppass123 -h mysql_slave < replication_setup.sql"
      ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 2s

  proxysql:
    build: ./proxysql
    image: proxysql:2.3.2
    container_name: proxysql
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
    networks:
      - autofailover
    ports:
      - target: 6032
        published: 6032
        mode: host
      - target: 6033
        published: 6033
        mode: host

volumes:
  orchestrator_db: {}
  mysql_master: {}
  mysql_slave: {}

networks:
  autofailover:
    driver: overlay
    ipam:
      config:
        - subnet: 10.1.18.0/24
