[Default]
http-bind-address = "0.0.0.0"
http-server = true
monitoring-save-config = true
# verbose = true

[Main]
db-servers-credential = "root:pass123" 
db-servers-hosts = "mysql_master:3306,mysql_slave:3306" 
force-slave-no-gtid-mode = false # Disable GTID in favor of positional replication
force-slave-readonly = true 
replication-credential = "replicator:pass123" 

monitoring-ticker = 1 # Monitoring delay

autorejoin = true 
autorejoin-backup-binlog = false 
# autorejoin-mysqldump = false 
autorejoin-script = "/opt/autorejoin-gtid.sh" 
autorejoin-slave-positional-hearbeat = false # Pseudo GTID, works in couple with positional replication

failover-falsepositive-ping-counter = 3 # Failover after 3 failed probes
failover-mode = "automatic" 
failover-readonly-state = true 

backup-mysqldump-options = "--hex-blob --single-transaction --verbose --all-databases --apply-slave-statements --master-data=1 --gtid --events=false"
monitoring-scheduler = true
scheduler-db-servers-logical-backup = true
scheduler-db-servers-logical-backup-cron = "0/5 * * * *"
scheduler-db-servers-physical-backup = false

proxysql = true
proxysql-bootstrap = true
proxysql-copy-grants = true
proxysql-password = "pass123"
proxysql-servers = "proxysql"
proxysql-user = "radmin"

# user = "root:005ccea88499d100d9022b0a33136ae9ae1ff0d1884ecee0f4b7"
