[Default]
http-bind-address = "0.0.0.0"
http-server = true
monitoring-save-config = true
# verbose = true

[Main]
db-servers-credential = "root:pass123"
db-servers-hosts = "mysql_master:3306,mysql_slave:3306"
failover-mode = "automatic"
replication-credential = "replicator:pass123"
autorejoin = true
autorejoin-backup-binlog = false
autorejoin-mysqldump = false
force-slave-readonly = true
# force-slave-no-gtid-mode = true
# autorejoin-slave-positional-hearbeat = true   # Pseudo GTID, works in couple with positional replication

autorejoin-script = "/opt/autorejoin-gtid.sh"

# user = "root:005ccea88499d100d9022b0a33136ae9ae1ff0d1884ecee0f4b7"
